# Generated by Django 6.0.3 on 2026-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('season', models.CharField(max_length=50)),
                ('sow_month', models.IntegerField()),
                ('harvest_month', models.IntegerField()),
                ('days_to_harvest', models.IntegerField()),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
